development:
  adapter: mysql
  encoding: utf8
  database: eastmedia_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: eastmedia_test
  username: root
  password:
  host: localhost
