development:
  adapter: mysql
  encoding: utf8
  database: nibbler_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: nibbler_test
  username: root
  password:
  host: localhost
