development:
  adapter: mysql
  encoding: utf8
  database: foo_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  database: foo_test
  username: root
  password:
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  database: foo_production
  username: root
  password: 
  host: localhost
